### ISSUE TITLE
[Feature request]: Add "Sleep" in Computer context menu

### ISSUE THREAD

**Issue by dessigndiffuse** [ClassicOldSong/moonlight-android#73]
### Is your feature request related to a problem? Please describe.

We can send wake-on-LAN but cant sleep the computer, i have created an application that runs command 
```
rundll32.exe powrprof.dll,SetSuspendState 0,1,0
```

but it is not ideal at it keeps idling on next launch and i have to quit session to get rid of it.

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/c3bde749-93e8-4f05-b528-47d0687ea6be)
Adding a Sleep option in this menu that runs command
```
rundll32.exe powrprof.dll,SetSuspendState 0,1,0
```

### Describe alternatives you've considered

Did not.

**Comment by ClassicOldSong** [comment]
You can run the sleep command on undo commands, so when you quit your stream, the computer goes to sleep as well. Or you can use server commands to sleep your computer.

**Comment by bernhardberger** [comment]
Sorry for necromancing this issue..

Can we somehow trigger a server command without connecting first?

I was about to open an FR for basically the same thing (only Shutdown vs Sleep).

I don't want to put the PC to sleep every time I quit the session (so doing this in "undo" seems impractical).


Reason: I'm usually streaming from one of my handhelds or other clients, quit the session but might still have some other processes running in the background. 
Then I go to bed and see my workstation still running but I don't want to mess with reconnecting because windows gets confused with window placement etc when connecting from another client and I have to shove all the windows around all over again when connecting back with my handheld the next day.

Maybe this can already be done without the need for a new feature but I can't see how.

**Comment by ClassicOldSong** [comment]
> Can we somehow trigger a server command without connecting first?

Nope, I didn't allow this specifically for safety concerns.

You can create a server command that sleeps for about 10 secs then execute the hibernation/shutdown, that allows you to have time to exit the stream manually.
